import turtle
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.left(60)
turtle.forward(23)
turtle.left(180)
turtle.forward(23)
turtle.right(60)
turtle.right(90)
turtle.left(45)
turtle.forward(27)
turtle.left(135)
turtle.forward(20)
turtle.up()
turtle.right(90)
turtle.forward(15)
turtle.down()
turtle.right(90)
turtle.forward(20)
turtle.forward(-10)
turtle.right(90)
turtle.back(5)
turtle.forward(60)

input('enter to con')
